const { chromium } = require('playwright');
const fs=require('fs');
const CMD=fs.readFileSync(process.argv[2]||'/tmp/eval_cmd.txt','utf8').trim();
const WAIT=parseInt(process.argv[3]||'14000',10);
(async()=>{
  const browser = await chromium.connectOverCDP('http://localhost:9222');
  const ctx = browser.contexts()[0];
  const page = ctx.pages().find(p=>p.url().includes('train-dev')) || ctx.pages()[0];
  await page.bringToFront().catch(()=>{});
  await page.locator('.xterm-screen, .xterm').first().click({force:true}).catch(()=>{});
  await page.waitForTimeout(300);
  await page.locator('.xterm-helper-textarea').first().focus().catch(()=>{});
  await page.keyboard.press('Control+C'); await page.waitForTimeout(400);
  await page.keyboard.insertText(CMD); await page.waitForTimeout(500);
  await page.keyboard.press('Enter');
  console.log('RAN len', CMD.length);
  await page.waitForTimeout(WAIT);
  const txt = await page.locator('.xterm-rows').first().innerText().catch(()=>'');
  console.log('TERM TAIL:\n'+txt.split('\n').filter(l=>l.trim()).slice(-35).join('\n'));
  await browser.close().catch(()=>{});
})().catch(e=>console.error('ERR',e.message));
